### PR TITLE
Fix issue #17

### PR DESCRIPTION
**Pull request by alvatar**

### CODE REVIEW

**Comment by alvatar** [comment]
Small fill for regression, @alexander-yakushev. Could you take a look at this please?
thank you!

**Comment by alvatar** [comment]
This seems to result in the build omitting the external aar. Any clue on how to fix that? (The nil parameter I  assume)

**Comment by alvatar** [comment]
Also using `:dependencies` in that parameter doesn't cut it. However, the AAR files are correctly unzipped, and can be found in aar-extracted directory.

**Comment by alexander-yakushev** [comment]
Could you please clarify the problem? Is this for possibility of including AARs not from the repositories?

**Comment by alvatar** [comment]
Sorry for the late response. I didn't receive a notification.
The issue is that I get classes not defined pointing  to those projects. They are from repositories, like SnappyDB.
When I manually copy the extracted files to the classes dir it seems to work IRCC.

**Pull request closed without merging**
